FROM nginx:1.15.9-alpine

# Remove any existing config files
RUN rm /etc/nginx/conf.d/*

# Copy config files
COPY config/nginx/default.dev.conf /etc/nginx/conf.d/default.conf

# Expose the listening port
EXPOSE 80

# Launch NGINX
CMD ["nginx", "-g", "daemon off;"]
