version: "3.8"

services:
  appweb:
    build:
      context: ../.
      dockerfile: docker/app/web/Dockerfile.dev
    image: myapp-appweb
    volumes:
      - /usr/src/app/node_modules
      - ../frontend/app/web:/usr/src/app:delegated
    ports:
      - "3000:3000"
    networks:
      - app-network
    tty: true

  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: myapp-server
    ports:
      - "80:80"
    depends_on:
      - appweb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
